{{- range $userName, $user := .Values.spec.users -}}
{{- range $queueAccessName, $queueAccess := $user.queueAccesses -}}
{{ if eq $queueAccess.default true }}
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: add-default-kueue-queue
  namespace: kubeflow-{{ $userName }}
spec:
  background: true
  rules:
    - name: add-queue-label
      skipBackgroundRequests: false
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              +(kueue.x-k8s.io/queue-name): {{ $queueAccessName }}
---
{{- end }}
{{- end }}
{{- end }}
