{{- range $userName, $user := .Values.spec.users -}}
{{- range $queueAccessName, $queueAccess := $user.queueAccesses -}}
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: {{ $queueAccessName }}
  namespace: kubeflow-{{ $userName }}
spec:
  clusterQueue: {{ $queueAccessName }}
---
{{ if eq $queueAccess.default true }}
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: default
  namespace: kubeflow-{{ $userName }}
spec:
  clusterQueue: {{ $queueAccessName }}
---
{{- end }}
{{- end }}
{{- end }}
